### ISSUE TITLE
Error 500 

### ISSUE THREAD

**Issue by jycemea** [JimmyReb/TemPi#1]
Hi JimmyReb. Many thanks for your tuto. 
Unfortunatly, it does not run in my config. I'm on a raspberry 2 B+ with Raspbian Wheezy installed.
Everything seems to be ok but at the end of your tuto, it is impossible to start the apache server...

The error is : 

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

I can read the temp my 2 sensors in /var/temperature/temps.log but imppossible to start the server.
I don't think it is an issue of permissions on the files (verified) but just on apache...

Can you help me please?

jycemea

**Comment by JimmyReb** [comment]
Hi jycemea

If you replace the /etc/apache2/sites-available/default file with the original does apache start?  You need to find out if this is an apache problem or something to do with the project.
Regards

Jim

**Comment by jycemea** [comment]
Hi. Of course Apache is running back normally if restore the original
config. I also tried to create a 2nd vhost (not as a default config) but
with a test domain (no-ip). The results are the same : internal server
error.
90%, I think there is an issue inside your default config file. I don't
think it is the app itselve.
I will test tomorrow under Raspbian Jessie.
If u think about something...

Thanks!
jycemea

**Comment by jycemea** [comment]
Hi. Solved !
The problem is coming from your default config ... as I suspected :) Sorry.
When you are replacing the default config file in apache, you are also replacing... the permissions.

**Solution :** don't do => sudo cp /var/temperature/default /etc/apache2/sites-available -f
but 
sudo cp default default.origin
sudo nano default  (here paste the content of your default file /var/temperature/default )
Ctrl + x + yes
sudo service apache2 reload


See u.

**Comment by nkhdk** [comment]
I'm having the "same" problem (as in I also get the Internal Server Error), however, the solution above doesn't work..

I set the LogLevel to debug and this is what I get when I 1) restart apache and 2) try to open the website:

`[Fri Aug 26 14:01:13 2016] [notice] Graceful restart requested, doing restart
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3154): Destroying interpreters.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3154): Cleanup interpreter ''.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3152): Destroying interpreters.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3152): Cleanup interpreter ''.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3154): Terminating Python.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3150): Destroying interpreters.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3150): Cleanup interpreter ''.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3154): Python has shutdown.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3152): Terminating Python.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3211): Destroying interpreters.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3211): Cleanup interpreter ''.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3150): Terminating Python.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3151): Destroying interpreters.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3151): Cleanup interpreter ''.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3153): Destroying interpreters.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3153): Cleanup interpreter ''.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3152): Python has shutdown.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3150): Python has shutdown.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3151): Terminating Python.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3211): Terminating Python.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3151): Python has shutdown.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3153): Terminating Python.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3149): Shutdown requested 'temperature'.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3149): Stopping process 'temperature'.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3149): Destroying interpreters.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3149): Cleanup interpreter ''.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3149): Terminating Python.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3211): Python has shutdown.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3153): Python has shutdown.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3149): Python has shutdown.
apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1 for ServerName
[Fri Aug 26 14:01:13 2016] [debug] mod_wsgi.c(10080): mod_wsgi (pid=3147): Socket for 'temperature' is '/var/run/apache2/wsgi.3147.1.1.sock'.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3736): Starting process 'temperature' with uid=33, gid=33 and threads=5.
[Fri Aug 26 14:01:13 2016] [notice] Apache/2.2.22 (Debian) PHP/5.4.45-0+deb7u4 mod_wsgi/3.3 Python/2.7.3 configured -- resuming normal operations
[Fri Aug 26 14:01:13 2016] [info] Server built: Jul 20 2016 16:35:00
[Fri Aug 26 14:01:13 2016] [debug] prefork.c(1023): AcceptMutex: sysvsem (default: sysvsem)
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3736): Initializing Python.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3737): Initializing Python.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3739): Initializing Python.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3738): Initializing Python.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3741): Initializing Python.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3740): Initializing Python.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3736): Attach interpreter ''.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3741): Attach interpreter ''.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3738): Attach interpreter ''.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3737): Attach interpreter ''.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3740): Attach interpreter ''.
[Fri Aug 26 14:01:13 2016] [info] mod_wsgi (pid=3739): Attach interpreter ''.
[Fri Aug 26 14:01:28 2016] [debug] mod_alias.c(482): [client 192.168.1.127] incomplete redirection target of '/temperature/' for URI '/' modified to 'http://192.168.1.122/temperature/'
[Fri Aug 26 14:01:28 2016] [info] [client 192.168.1.127] mod_wsgi (pid=3736, process='temperature', application=''): Loading WSGI script '/var/www/html/temperature/temperature.wsgi'.
[Fri Aug 26 14:01:29 2016] [info] mod_wsgi (pid=3754): Initializing Python.
[Fri Aug 26 14:01:29 2016] [error] /usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.babel is deprecated, use flask_babel instead.
[Fri Aug 26 14:01:29 2016] [error]   .format(x=modname), ExtDeprecationWarning
[Fri Aug 26 14:01:29 2016] [info] mod_wsgi (pid=3754): Attach interpreter ''.
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127] [2016-08-26 14:01:30,247] ERROR in app: Exception on / [GET]
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127] Traceback (most recent call last):
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127]     response = self.full_dispatch_request()
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127]     rv = self.handle_user_exception(e)
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127]     reraise(exc_type, exc_value, tb)
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127]     rv = self.dispatch_request()
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127]     return self.view_functions[rule.endpoint](**req.view_args)
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127]   File "/var/www/html/temperature/index.py", line 133, in show_main
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127]     maximo = get_data(option, "max(temp)", "oneasfloat")
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127]   File "/var/www/html/temperature/index.py", line 522, in get_data
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127]     return float(rows[0])
[Fri Aug 26 14:01:30 2016] [error] [client 192.168.1.127] ValueError: invalid literal for float(): 28.0-
[Fri Aug 26 14:01:30 2016] [debug] mod_deflate.c(700): [client 192.168.1.127] Zlib: Compressed 291 to 200 : URL /temperature/
`
I have two combined temperatur and humidity sensors (in my setup I call them TA and TB) and one combined temperature and barometric pressure sensor (here called BA). In /var/temperature/temps.log I get output like this from them:

`Aug 26, 2016  1:41PM
aBABAR1014.6

Aug 26, 2016  1:41PM
BA TEMP 025.8

Aug 26, 2016  1:42PM
aTARHUM54.1-

Aug 26, 2016  1:42PM
TA TEMP 27.4-

Aug 26, 2016  1:44PM
aTBRHUM54.8-

Aug 26, 2016  1:44PM
TB TEMP 27.1-

Aug 26, 2016  1:54PM
aTBRHUM55.0-

Aug 26, 2016  1:54PM
TB TEMP 27.1-
`

Any idea what's going wrong?

**Comment by JimmyReb** [comment]
Server 500 is a generic server error.  Are you using Raspian Wheezy for the OS?

**Comment by nkhdk** [comment]
I'm on the Raspian Jessy version from may (but this is a fresh install), I had to run _apt-get update_ and _apt-get upgrade_ to get flask installed though...

Is Wheezy available for download still?

**Comment by JimmyReb** [comment]
My guess is there is issues with the apache server config file.  On wheezy it is  /etc/apache2/sites-available/default.  Put the original file back and see if apache starts correctly.  I'm no apache guru so I can't help, sorry.  If you get the config file sorted then post it here for others.  Thanks.

**Comment by nkhdk** [comment]
Okay, Apache works fine with the original server config, so I'll investigate further. Thanks for trying to help!
